services:
  bun-app:
    build: .
    container_name: bun-container
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - node_modules:/app/node_modules

    command: ["bun", "dev"]
volumes:
  node_modules:
